interface Env {
	MCP_OBJECT: DurableObjectNamespace;
	OAUTH_KV: KVNamespace;
	HTTP_LOG_BUCKET: R2Bucket;
	WAF_LOG_BUCKET: R2Bucket;
	ACCESS_CLIENT_ID: string;
	ACCESS_CLIENT_SECRET: string;
	ACCESS_TOKEN_URL: string;
	ACCESS_AUTHORIZATION_URL: string;
	ACCESS_JWKS_URL: string;
	COOKIE_ENCRYPTION_KEY: string;
	MATCHED_PAYLOAD_PRIVATE_KEY: string;
}
